language: node_js
node_js:
- '0.12'
sudo: false
after_success:
- gulp coverage
deploy:
  provider: npm
  email: d2ltravisdeploy@d2l.com
  api_key:
    secure: NY9v4U8k4N9VKHTmYxnGeLT860amhm70H1F5ZA55t9zfRbEyE/jWcM+oR1cH65IhWFj+QxCSCh16QTScLnfiWP4w4TIeG1b70bY8mkw8lx+eeOzISoZylI7BmqnJRdMoJxr6tjCKgEQW71wRn1xxYZaaEgGZA10cJdhsxGYxEzI=
  on:
    tags: true
    all_branches: true
