language: node_js
node_js:
- '0.10'
after_success:
- gulp coverage
deploy:
  provider: npm
  email: d2ltravisdeploy@d2l.com
  api_key:
    secure: T619z2cz2HgXROdDtzDkheikIK+B96ukczb3RFYAeHvvmK5UvXssHH9r13IzjtGMmvGP3hgkiQg397VDUYXAhl8fkSrHxiDkGARAZt2oFyMPPRPMWWoZfiwG59SK1TXpiRdiXoQzth68E8i+ojEF/k1ZZmEz0Ix2khR3ODOiDow=
  on:
    tags: true
    all_branches: true
